### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by rachelaronoff** [StreetScienceCommunity/StreetScienceCommunity.github.io#41]
hi!  just a quick note to say the word Hackuarium is missing a 'u' on your page about your BeerDeCoded event.  Thanks for your attention to this matter!

Great that you are 'cloning' this project (in a sense) btw!
(We too have been playing with the Minion around the Open Food Repo Project!)
best,
Rachel
p.s. btw, I am acting president and biosec officer for Hackuarium!

**Comment by bgruening** [comment]
@rachelaronoff nice to see you here. I have fixed that in https://github.com/StreetScienceCommunity/StreetScienceCommunity.github.io/commit/a09ddf3e63a9ef1f5bcd569ad7d853d72776ae82

Hope we see you soon in Freiburg! :)
